### ISSUE TITLE
Failed to find Android SDK on Mac

### ISSUE THREAD

**Issue by rikoe** [Redth/dotnet-maui-check#22]
I have followed all the instructions in the relevant docs, but I still get the following:

```
🔎 Android SDK Checkup...
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: `/Users/riko/Library/Developer/Xamarin/android-sdk-macosx`, result=True
ValidateAndroidSdkLocation: `/Users/riko/Library/Developer/Xamarin/android-sdk-macosx`, result=True
ValidateJavaSdkLocation: `/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home`, result=True
ValidateAndroidNdkLocation: ``, result=False
Best NDK selected: v21.3.6528147 in /Users/riko/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle
ValidateAndroidNdkLocation: `/Users/riko/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle`, result=True

──────────────────────────────────────────────────────────────────────────────
💉 Recommendation: Install the Android SDK
For more information see: https://aka.ms/dotnet-androidsdk-help
──────────────────────────────────────────────────────────────────────────────


❌ Skipped: Android Emulator

Checkup had Error status: androidsdk
androidsdk: Failed to find Android SDK.
🔔 There were one or more problems detected.
Please review the errors and correct them and run maui-check again.
```

Is there anything that I am missing?

**Comment by Redth** [comment]
Thanks, try updating to 0.4.2 which should resolve this issue.

**Comment by rikoe** [comment]
Thanks, 0.4.2 works.

I now get the following error regarding the emulator:

```
🔎 Android SDK Checkup...
ValidateAndroidSdkLocation: ``, result=False
ValidateAndroidSdkLocation: `/Users/riko/Library/Developer/Xamarin/android-sdk-macosx`, result=True
ValidateAndroidSdkLocation: `/Users/riko/Library/Developer/Xamarin/android-sdk-macosx`, result=True
ValidateJavaSdkLocation: `/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home`, result=True
ValidateAndroidNdkLocation: ``, result=False
Best NDK selected: v21.3.6528147 in /Users/riko/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle
ValidateAndroidNdkLocation: `/Users/riko/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle`, result=True
SetEnvironmentVariable: ANDROID_SDK_ROOT=/Users/riko/Library/Developer/Xamarin/android-sdk-macosx
SetEnvironmentVariable: ANDROID_HOME=/Users/riko/Library/Developer/Xamarin/android-sdk-macosx
  ✔ emulator (30.1.5)
  ✔ build-tools;30.0.2 (30.0.2)
  ✔ platforms;android-30 (3)
  ✔ system-images;android-30;google_apis;x86 (9)
  ✔ platform-tools (30.0.4)

🔎 Android Emulator Checkup...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
  ❌ Android Emulator - x86 - API30 - Google API's not created.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

──────────────────────────────────────────────────────────────────────────────
💉 Recommendation: Create an Android Emulator
──────────────────────────────────────────────────────────────────────────────

🔔 Attempt to fix? [y/n] (y): y
⏳ Attempting to fix: Android Emulator
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
Fix applied.  Checking again...

🔎 Android Emulator Checkup...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
  ❌ Android Emulator - x86 - API30 - Google API's not created.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

──────────────────────────────────────────────────────────────────────────────
💉 Recommendation: Create an Android Emulator
─────────────────────────────────────────
```
